### ISSUE TITLE
Media Item

### ISSUE THREAD

**Issue by rikschennink** [Frankwarnaar/minor-cssttr#4]
Een lijst met media items is nog prettiger te navigeren als heel het item klikbaar is. Kan zonder de HTML aan te passen...

**Comment by Frankwarnaar** [comment]
Door het anchor element absoluut en zijn container relatief te positioneren, komt het anchor element los uit zijn flow. Hierdoor gaan allerlei dingen overflowen. Ik ben er toch voorstander van daarom om het <a> element om het artikel te plaatsen.
